# This is a basic workflow to help you get started with Actions

name: GH Action Test 

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        node: [14, 16]
        os: [ubuntu-latest]

    steps:
    - id: test-command
      name: Test a command 
      run: npm help
